apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dontwork 
  labels:
    app: ubuntu
spec:
  containers:
  - image: ghcr.io/p/busy-box:latest
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu-dontwork
  restartPolicy: Always
